name: Store egzamin directory in Drive
on:
  push: { branches: [main] }
jobs:
  buildAndTestForSomePlatforms:
    name: Upload egzamin directory to drive
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
      # Upload to Drive
      - name: Upload egzamin folder to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: egzamin
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          folder: ${{ secrets.GSA_FOLDER_ID }}
